name: bottom_nav_bar
description: An easy-to-use and clean bottom navigation bar.
version: 1.0.0
homepage: https://github.com/imsujan276/bottom_nav_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
